#cloud-config

users:
  - name: usr_admin
    shell: /bin/bash
    sudo: ALL=(ALL:ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF0xMS+8L4ez3jdXTlCuqSLUi0KIdZM0zoDZo3R50wNl usr_admin

chpasswd:
  list: |
    root:*
  expire: false

ssh_pwauth: false

bootcmd:
  - mkdir -p /etc/etcd/ssl

write_files:
  - path: /etc/profile.d/etcdctl.sh
    permissions: '0644'
    content: |
      export ETCDCTL_API=3
      export ETCDCTL_ENDPOINTS=https://127.0.0.1:2379
      export ETCDCTL_CACERT=/etc/etcd/ssl/ca.crt
      export ETCDCTL_CERT=/etc/etcd/ssl/etcd.crt
      export ETCDCTL_KEY=/etc/etcd/ssl/etcd.key
  - path: /etc/etcd/ssl/ca.crt
    encoding: b64
    content: ${ca_crt}
    permissions: '0644'
  - path: /etc/etcd/ssl/etcd.crt
    encoding: b64
    content: ${node_crt}
    permissions: '0644'
  - path: /etc/etcd/ssl/etcd.key
    encoding: b64
    content: ${node_key}
    permissions: '0600'
  - path: /var/lib/postgresql/ssl/server.crt
    encoding: b64
    content: ${server_crt}
    permissions: '0644'
  - path: /var/lib/postgresql/ssl/server.key
    encoding: b64
    content: ${server_key}
    permissions: '0600'
  - path: /var/lib/postgresql/ssl/server.req
    encoding: b64
    content: ${server_req}
    permissions: '0600'
  - path: /etc/patroni/config.yml
    encoding: b64
    content: ${patroni_cnf}
    permissions: '0644'
  - path: /etc/etcd/etcd.env
    encoding: b64
    content: ${etcd_env}
    permissions: '0644'
  - path: /etc/systemd/system/etcd.service
    encoding: b64
    content: ${etcd_service}
    permissions: '0644'


packages:
  - openssh-server
  - rsync
  - openssl
  - postgresql-common

package_update: true
package_upgrade: true

timezone: UTC

final_message: "VM is ready!"

runcmd:
  - set -x

  # PostgreSQL installation
  - apt-get update
  - echo "" | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
  - apt-get install -y postgresql-17 postgresql-contrib
  - echo "postgres download ended, continuing postgres isntallation" | wall &
  - mkfs.ext4 /dev/vdb
  - mkdir -p /mnt/pgdata
  - mount /dev/vdb /mnt/pgdata
  - mkdir -p /mnt/pgdata/data
  - chown -R postgres:postgres /mnt/pgdata
  - chmod 700 /mnt/pgdata/data
  - echo "/dev/vdb /mnt/pgdata ext4 defaults 0 2" >> /etc/fstab
  - chown postgres:postgres /mnt/pgdata
  - systemctl stop postgresql
  - systemctl disable postgresql
  - echo "postgres setup finished on $(hostname) at $(date), starting etcd installation" | wall &

  # etcd
  - wget https://github.com/etcd-io/etcd/releases/download/v3.5.17/etcd-v3.5.17-linux-amd64.tar.gz
  - tar xvf etcd-v3.5.17-linux-amd64.tar.gz
  - mv etcd-v3.5.17-linux-amd64/etcd etcd-v3.5.17-linux-amd64/etcdctl /usr/local/bin/
  - rm -rf etcd-v3.5.17-linux-amd64 etcd-v3.5.17-linux-amd64.tar.gz
  - mkfs.ext4 /dev/vdc
  - mkdir -p /mnt/etcddata
  - mount /dev/vdc /mnt/etcddata
  - echo "/dev/vdc /mnt/etcddata ext4 defaults 0 2" >> /etc/fstab
  - useradd --system --home /mnt/etcddata --shell /bin/false etcd
  - mkdir -p /var/lib/etcd
  - chown -R etcd:etcd /etc/etcd
  - chown -R etcd:etcd /mnt/etcddata
  - systemctl daemon-reload
  - systemctl enable etcd
  - systemctl start etcd
  - echo "etcd setup finished on $(hostname) at $(date), starting postgres certs config" | wall &

  # Postgres certs
  # - mkdir -p /var/lib/postgresql/data
  - mkdir -p /var/lib/postgresql/ssl
  - chown postgres:postgres /var/lib/postgresql/data
  - chown postgres:postgres /var/lib/postgresql/ssl/server.*
  - chmod 700 /var/lib/postgresql/data
  - apt update 
  - apt install -y acl
  - setfacl -m u:postgres:r /etc/etcd/ssl/ca.crt
  - setfacl -m u:postgres:r /etc/etcd/ssl/etcd.crt
  - setfacl -m u:postgres:r /etc/etcd/ssl/etcd.key
  - echo "postgres certs setup finished on $(hostname) at $(date), starting patroni config" | wall &

  # Patroni certs
  - apt install -y patroni
  - mkdir -p /etc/patroni/
  - sh -c 'cat /var/lib/postgresql/ssl/server.crt /var/lib/postgresql/ssl/server.key > /var/lib/postgresql/ssl/server.pem'
  - chown postgres:postgres /var/lib/postgresql/ssl/server.pem
  - chmod 600 /var/lib/postgresql/ssl/server.pem
  - echo "patroni certs setup finished on $(hostname) at $(date), starting patroni and HA cluster" | wall &

  # Starting patroni and HA cluster
  - systemctl restart patroni
  - sed -i '/ETCD_INITIAL_CLUSTER_STATE/s/new/existing/' /etc/etcd/etcd.env
  - echo "HA postgres cluster started" | wall &
